/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // weAId Material 3 maroon palette (from Stitch)
        'on-tertiary': '#ffffff',
        secondary: '#5d5f5f',
        'surface-variant': '#f7ddd8',
        'secondary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#bcc2ff',
        'surface-container': '#ffe9e6',
        'on-primary-container': '#ff8371',
        'inverse-primary': '#ffb4a8',
        'surface-container-low': '#fff0ee',
        'on-tertiary-fixed-variant': '#1830c2',
        outline: '#8e706c',
        'on-secondary-fixed': '#1a1c1c',
        'surface-tint': '#b22b1d',
        'secondary-container': '#dcdddd',
        error: '#ba1a1a',
        'on-secondary-container': '#5f6161',
        'on-secondary-fixed-variant': '#454747',
        'on-primary-fixed-variant': '#8f0f07',
        'on-error': '#ffffff',
        'on-primary-fixed': '#410000',
        tertiary: '#00137f',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'outline-variant': '#e2bfb9',
        background: '#fff8f6',
        'surface-bright': '#fff8f6',
        'on-surface': '#261816',
        'primary-fixed': '#ffdad4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#000c61',
        'tertiary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#ffb4a8',
        'inverse-on-surface': '#ffedea',
        'surface-container-highest': '#f7ddd8',
        'on-surface-variant': '#5a413d',
        'surface-container-high': '#fde2de',
        primary: '#570000',
        'on-tertiary-container': '#94a0ff',
        'error-container': '#ffdad6',
        'surface-dim': '#eed4d0',
        surface: '#fff8f6',
        'secondary-fixed-dim': '#c6c6c7',
        'on-primary': '#ffffff',
        'on-background': '#261816',
        'tertiary-container': '#0021b9',
        'inverse-surface': '#3d2d2a',
        'primary-container': '#800000',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        unit: '8px',
        'stack-md': '16px',
        gutter: '16px',
        'container-padding': '20px',
        'stack-lg': '24px',
      },
      fontFamily: {
        'headline-sm': ['Montserrat', 'sans-serif'],
        'label-bold': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'ai-signature': ['Montserrat', 'sans-serif'],
        'display-md': ['Montserrat', 'sans-serif'],
        sans: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'ai-signature': ['inherit', { lineHeight: 'inherit', fontWeight: '900' }],
        'display-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      boxShadow: {
        card: '0 4px 12px rgba(128,0,0,0.04)',
        hero: '0 4px 12px rgba(128,0,0,0.10)',
        'nav-top': '0 -4px 12px rgba(128,0,0,0.04)',
      },
      keyframes: {
        glow: {
          '0%, 100%': { textShadow: '0 0 5px rgba(255,255,255,0.7)' },
          '50%': { textShadow: '0 0 15px rgba(255,255,255,1), 0 0 25px rgba(255,255,255,0.5)' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: 0.6 },
          '50%': { opacity: 1 },
        },
      },
      animation: {
        glow: 'glow 3s ease-in-out infinite',
        'pulse-slow': 'pulse-slow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
